CREATE TABLE CUSTOMER(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    last_valid_till timestamp
);

CREATE TABLE CODE(
    customer_id integer references customer(id),
    code text not null,
    valid_from timestamp not null,
    valid_till timestamp not null
);

CREATE INDEX code_customer_id  on code USING HASH (customer_id);
